backend:
  name: github
  repo: byvasco/mark2

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"


collections:
  - name: "stories"
    label: "Stories"
    folder: content/stories
    create: true
    fields:
      - name: title
        label: Title
      
      - name: date
        label: Date
        widget: datetime

      - name: cover
        label: Cover
      
      - name: body
        label: Body
        widget: markdown